### ISSUE TITLE
Cannot compile with PHP 5.5

### ISSUE THREAD

**Issue by juamedgod** [eaccelerator/eaccelerator#33]
It is complaining with:

eaccelerator.c:66:23: error: php_logos.h: No such file or directory

Checking the php-5.5.0/UPGRADING:
- php_logo_guid(), php_egg_logo_guid(), php_real_logo_guid() and
  zend_logo_guid() have been removed
