### ISSUE TITLE
Compilation error recipe for target 'eaccelerator.lo' failed

### ISSUE THREAD

**Issue by rz300** [eaccelerator/eaccelerator#50]
Do not work with PHP Version 5.6.9-0+deb8u1

```
make install
/bin/bash /home/anubis/eaccelerator/libtool --mode=compile cc  -I. -I/home/anubis/eaccelerator -DPHP_ATOM_INC -I/home/anubis/eaccelerator/include -I/home/anubis/eaccelerator/main -I/home/anubis/eaccelerator -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/anubis/eaccelerator/eaccelerator.c -o eaccelerator.lo
libtool: compile:  cc -I. -I/home/anubis/eaccelerator -DPHP_ATOM_INC -I/home/anubis/eaccelerator/include -I/home/anubis/eaccelerator/main -I/home/anubis/eaccelerator -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/anubis/eaccelerator/eaccelerator.c  -fPIC -DPIC -o .libs/eaccelerator.o
/home/anubis/eaccelerator/eaccelerator.c:66:23: fatal error: php_logos.h: No such file or directory
 #include "php_logos.h"
                       ^
compilation terminated.
Makefile:193: recipe for target 'eaccelerator.lo' failed
make: *** [eaccelerator.lo] Error 1
```

**Comment by jesuGMZ** [comment]
"The master branch supports PHP 5.4." from Wikipedia and you can check the last source change date.

"PHP 5.6 was release in 2014" [2]

So eAccelerator not supports PHP 5.6.

[1] https://github.com/eaccelerator/eaccelerator
[2] https://en.wikipedia.org/wiki/PHP#Release_history
